spring:
  datasource:
    druid:
      url: jdbc:mysql://8.210.44.10:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: test
      password: aq$iJF2^RJ
      driver-class-name: com.mysql.jdbc.Driver
